# Generated by Django 4.2.5 on 2023-09-14 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_product', models.CharField(help_text='Name of the food product', max_length=100, null=True)),
                ('food_company', models.CharField(help_text='Food Manufactuing company', max_length=100, null=True)),
                ('author', models.CharField(help_text='Name of the contributing entity', max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='images')),
                ('add_date', models.DateField(default=django.utils.timezone.now, help_text='Enter field published_date')),
                ('result', models.CharField(help_text='The Result of OCR', max_length=800, null=True)),
                ('is_ocred', models.BooleanField(default=False)),
            ],
        ),
    ]
